from _typeshed import Incomplete
from typing import Any, List, Optional, Tuple

from mmcif.api.DataCategoryTyped import DataCategoryHints as DataCategoryHints, DataCategoryTyped as DataCategoryTyped
from mmcif.api.PdbxContainers import CifName as CifName, DataContainer
from mmcif.io.BinaryCifReader import BinaryCifDecoders as BinaryCifDecoders
from mmcif.api.DictionaryApi import DictionaryApi

logger: Incomplete

class BinaryCifWriter:
    def __init__(self, dictionaryApi: DictionaryApi, storeStringsAsBytes: bool = False, defaultStringEncoding: str = 'utf-8', applyTypes: bool = True, useStringTypes: bool = False, useFloat64: bool = False, copyInputData: bool = False, ignoreCastErrors: bool = False, **kwargs: Any) -> None: ...
    def serialize(self, filePath: str, containerList: List[DataContainer]) -> bool: ...

class TypedArray:
    data: List[Any]
    dtype: str
    def __init__(self, data: List[Any], dtype: Optional[str] = None) -> None: ...

class BinaryCifEncoders:
    def __init__(self, defaultStringEncoding: str = 'utf-8', storeStringsAsBytes: bool = True, useFloat64: bool = False) -> None: ...
    # def encode(self, colDataList, encodingTypeList, dataType): ...
    # def encodeWithMask(self, colDataList, colMaskList, encodingType): ...
    # def byteArrayEncoder(self, colDataList, dataType): ...
    # def byteArrayEncoderTyped(self, colTypedDataList, dataType): ...
    # def deltaEncoder(self, colDataList, minLen: int = 40): ...
    # def deltaEncoderTyped(self, colTypedDataList, minLen: int = 40): ...
    # def runLengthEncoder(self, colDataList, minLen: int = 40): ...
    # def runLengthEncoderTyped(self, colTypedDataList, minLen: int = 40): ...
    # def stringArrayMaskedEncoder(self, colDataList, colMaskList): ...
    # def intArrayMaskedEncoder(self, colDataList, colMaskList): ...
    # def floatArrayMaskedEncoder(self, colDataList, colMaskList): ...
    # def getMask(self, colDataList): ...
    # def integerPackingEncoder(self, colDataList): ...
    # def integerPackingEncoderTyped(self, colTypedDataList: TypedArray) -> Tuple[TypedArray, str]: ...
