from _typeshed import Incomplete
from typing import Any, Dict, List, Optional
from collections.abc import Generator
from mmcif.api.DataCategory import DataCategory as DataCategory
from mmcif.api.PdbxContainers import DataContainer as DataContainer

logger: Incomplete

class BinaryCifReader:
    def __init__(self, storeStringsAsBytes: bool = False, defaultStringEncoding: str = 'utf-8') -> None: ...
    def deserialize(self, locator: str, timeout: Optional[float] = None) -> List[DataContainer]: ...

class BinaryCifDecoders:
    bCifCodeTypeD: Incomplete
    bCifTypeD: Incomplete
    def __init__(self, storeStringsAsBytes: bool = False, defaultStringEncoding: str = 'utf-8', verbose: bool = False) -> None: ...
    def decode(self, colDataList: List[str], encodingDictList: Dict[str, str]) -> List[Any]: ...
    # def stringArrayDecoder(self, colDataList, encodingDict) -> Generator[Incomplete]: ...
    # def byteArrayDecoder(self, colDataList, encodingDict): ...
    # def integerPackingDecoder(self, colDataList, encodingDict): ...
    # def deltaDecoder(self, colDataList, encodingDict) -> Generator[Incomplete]: ...
    # def runLengthDecoder(self, colDataList, encodingDict) -> Generator[Incomplete]: ...
    # def fixedPointDecoder(self, colDataList, encodingDict) -> Generator[Incomplete]: ...
    # def intervalQuantizationDecoder(self, colDataList, encodingDict) -> Generator[Incomplete]: ...
