from _typeshed import Incomplete
# from mmcif.core.mmciflib import ParseCifSimple as ParseCifSimple

__docformat__: str
logger: Incomplete

class CifFile:
    def __init__(self, fileName, parseLogFileName=None) -> None: ...
    def getCifFile(self): ...
    @classmethod
    def getFileExt(cls): ...
    def write(self, fileName) -> None: ...
    @classmethod
    def read(cls, fileName): ...
