from _typeshed import Incomplete
from typing import List, Optional, TextIO, Union

from mmcif.api.DataCategoryFormatted import DataCategoryFormatted as DataCategoryFormatted
from mmcif.api.PdbxContainers import ContainerBase, DataContainer
from mmcif.io.PdbxExceptions import PdbxError as PdbxError

__docformat__: str
logger: Incomplete

class PdbxWriter:
    def __init__(self, ofh: TextIO = ...) -> None: ...
    def setSetEnforceAscii(self, boolVal: bool) -> None: ...
    def setConvertCharRefs(self, flag: bool) -> None: ...
    def setUseStopTokens(self, flag: bool) -> None: ...
    def setMaxLineLength(self, numChars: int) -> None: ...
    def setAlignmentFlag(self, flag: bool = True) -> None: ...
    def setPreferSingleQuotes(self) -> None: ...
    def setPreferDoubleQuotes(self) -> None: ...
    def setRowPartition(self, numParts: Optional[int]) -> None: ...
    def write(self, containerList: List[ContainerBase], lastInOrder: Optional[List[str]]=None, selectOrder: Optional[List[str]]=None) -> None: ...
    def writeContainer(self, container: ContainerBase, lastInOrder: Optional[List[str]]=None, selectOrder: Optional[List[str]]=None) -> None: ...
