from typing import Any, ClassVar, Dict, List, overload

A: type
D: type
eTYPE_CODE_BIGINT: eTypeCode
eTYPE_CODE_DATETIME: eTypeCode
eTYPE_CODE_FLOAT: eTypeCode
eTYPE_CODE_INT: eTypeCode
eTYPE_CODE_NONE: eTypeCode
eTYPE_CODE_STRING: eTypeCode
eTYPE_CODE_TEXT: eTypeCode

Serializer = Any
eFileMode = str

class Block:
   @overload
   def __init__(self, name: str, serP: Serializer, fileMode: eFileMode, caseSense: bool) -> None: ...
   @overload
   def __init__(self, arg0: str, arg1: Serializer) -> None: ...
   @overload
   def __init__(self, arg0: str, arg1: Serializer, arg2: eFileMode) -> None: ...
   @overload
   def AddTable(self, name: str, colCaseSense: bool) -> ISTable: ...
   @overload
   def AddTable(self) -> ISTable: ...
   @overload
   def AddTable(self, arg0: str) -> ISTable: ...
   def DeleteTable(self, tableName: str) -> None: ...
   def GetName(self) -> str: ...
   def GetTable(self, tableName: str) -> ISTable: ...
   def GetTableNames(self, tableNames: list[str]) -> list[str]: ...
   def GetTablePtr(self, tableName: str) -> ISTable: ...
   def IsTablePresent(self, tableName: str) -> bool: ...
   def Print(self) -> None: ...
   def RenameTable(self, oldName: str, newName: str) -> None: ...
   def SetName(self, name: str) -> None: ...
   @overload
   def WriteTable(self, isTable: ISTable) -> ISTable: ...
   @overload
   def WriteTable(self, isTableP: ISTable) -> None: ...
   # def __eq__(self, inBlock: Block) -> list[tuple[str, ISTable.eTableDiff]]: ...

#class CifDataInfo:
##    def __init__(self, dictFile: DicFile) -> None: ...
 #   def GetCatAttribute(self, catName: str, refCatName: str, refAttrName: str) -> list[str]: ...
 #   def GetCatKeys(self, catName: str) -> list[str]: ...
 #   def GetCatNames(self) -> list[str]: ...
 #   def GetItemAttribute(self, itemName: str, refCatName: str, refAttrName: str) -> list[str]: ...
 #   def GetItemsNames(self) -> list[str]: ...
 #   def GetVersion(self, version: str) -> str: ...
 #   def IsCatDefined(self, catName: str) -> bool: ...
 #   def IsItemDefined(self, itemName: str) -> bool: ...

class CifFile(TableFile):
    class eQuoting:
        # __members__: ClassVar[dict] = ...  # read-only
        # __entries: ClassVar[dict] = ...
        eDOUBLE: ClassVar[CifFile.eQuoting] = ...
        eSINGLE: ClassVar[CifFile.eQuoting] = ...
        def __init__(self, value: int) -> None: ...
        def __eq__(self, other: object) -> bool: ...
        def __hash__(self) -> int: ...
        def __index__(self) -> int: ...
        def __int__(self) -> int: ...
        def __ne__(self, other: object) -> bool: ...
        @property
        def name(self) -> str: ...
        @property
        def value(self) -> int: ...
    eDOUBLE: ClassVar[CifFile.eQuoting] = ...
    eSINGLE: ClassVar[CifFile.eQuoting] = ...
    @overload
    def __init__(self, fileMode: eFileMode, fileName: str, verbose: bool, caseSense: str, maxLineLength: int, nullValue: str) -> None: ...
    @overload
    def __init__(self, arg0: eFileMode, arg1: str) -> None: ...
    @overload
    def __init__(self, arg0: eFileMode, arg1: str, arg2: bool) -> None: ...
    @overload
    def __init__(self, arg0: eFileMode, arg1: str, arg2: bool, arg3: bool) -> None: ...
    @overload
    def __init__(self, arg0: eFileMode, arg1: str, arg2: bool, arg3: bool, arg4: int) -> None: ...
    @overload
    def __init__(self, verbose: bool, caseSense: str, maxLineLength: int, nullValue: str) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: bool) -> None: ...
    @overload
    def __init__(self, arg0: bool, arg1: bool) -> None: ...
    @overload
    def __init__(self, arg0: bool, arg1: bool, arg2: int) -> None: ...
    @overload
    def __init__(self, fake: bool, verbose: bool, intCaseSense: int, maxLineLength: int, nullValue: str) -> None: ...
    # @overload
    # def __init__(self, arg0: bool, arg1: bool) -> None: ...
    # @overload
    # def __init__(self, arg0: bool, arg1: bool, arg2: int) -> None: ...
    @overload
    def __init__(self, arg0: bool, arg1: bool, arg2: int, arg3: int) -> None: ...
    def DataChecking(self, dicRef: CifFile, diagFileName: str, extraDictChecks: bool, extraCifChecks: bool) -> tuple[int, CifFile]: ...
    # def FindCifNullRows(self, nullRowsIndices: list[int], isTable: ISTable) -> list[int]: ...
    # def GetAttributeValue(self, attribVal: str, blockId: str, category: str, attribute: str) -> str: ...
    def GetAttributeValueIf(self, attribVal: str, blockId: str, category: str, attributeA: str, attributeB: str, valB: str) -> str: ...
    def GetAttributeValues(self, strings: list[str], blockId: str, category: str, attribute: str) -> list[str]: ...
    def GetAttributeValuesIf(self, strings: list[str], blockId: str, category: str, attributeA: str, attributeB: str, valB: str) -> list[str]: ...
    def GetEnumCheck(self) -> bool: ...
    def GetLooping(self, catName: str) -> bool: ...
    def GetParsingDiags(self) -> str: ...
    def GetQuoting(self) -> int: ...
    def GetSrcFileName(self) -> str: ...
    def GetVerbose(self) -> bool: ...
    def IsAttributeValueDefined(self, blockId: str, category: str, attribute: str) -> bool: ...
    def IsSmartPrint(self) -> bool: ...
    @overload
    def SetAttributeValue(self, blockId: str, category: str, attribute: str, value: str, create: bool) -> None: ...
    @overload
    def SetAttributeValue(self, arg0: str, arg1: str, arg2: str, arg3: str) -> None: ...
    @overload
    def SetAttributeValueIf(self, blockId: str, category: str, attributeA: str, valA: str, attributeB: str, valB: str, create: bool) -> None: ...
    @overload
    def SetAttributeValueIf(self, arg0: str, arg1: str, arg2: str, arg3: str, arg4: str, arg5: str) -> None: ...
    def SetAttributeValueIfNull(self, blockId: str, category: str, attribute: str, value: str) -> None: ...
    def SetAttributeValues(self, blockId: str, category: str, attribute: str, values: list[str]) -> None: ...
    @overload
    def SetEnumCheck(self, caseSense: bool) -> None: ...
    @overload
    def SetEnumCheck(self) -> None: ...
    @overload
    def SetLooping(self, catName: str, looping: bool) -> None: ...
    @overload
    def SetLooping(self, arg0: str) -> None: ...
    def SetQuoting(self, quoting: CifFile.eQuoting) -> None: ...
    @overload
    def SetSmartPrint(self, smartPrint: bool) -> None: ...
    @overload
    def SetSmartPrint(self) -> None: ...
    def SetSrcFileName(self, srcFileName: str) -> None: ...
    @overload
    def Write(self, cifFileName: str, sortTables: bool, writeEmptyTables: bool) -> None: ...
    @overload
    def Write(self, arg0: str) -> None: ...
    @overload
    def Write(self, arg0: str, arg1: bool) -> None: ...
    @overload
    def Write(self, cifFileName: str, tableOrder: list[str], writeEmptyTables: bool) -> None: ...
    @overload
    def Write(self, arg0: str, arg1: list[str]) -> None: ...
    @overload
    def WriteNmrStar(self, nmrStarFileName: str, globalBlockName: str, sortTables: bool, writeEmptyTables: bool) -> None: ...
    @overload
    def WriteNmrStar(self, arg0: str, arg1: str) -> None: ...
    @overload
    def WriteNmrStar(self, arg0: str, arg1: str, arg2: bool) -> None: ...

# class CifFileReadDef:
#     @overload
#     def __init__(self, dblist: list[str], clist: list[str], dbtype: type, ctype: type) -> None: ...
#     @overload
#     def __init__(self, arg0: list[str], arg1: list[str]) -> None: ...
#     @overload
#     def __init__(self, arg0: list[str], arg1: list[str], arg2: type) -> None: ...
#     @overload
#     def __init__(self) -> None: ...
#     def AreAllCatsRead(self) -> int: ...
#     def Category_OK(self, categoryName: str) -> int: ...
#     def Datablock_OK(self, datablockName: str) -> int: ...
#     def IncreaseNumReadCats(self) -> None: ...
#     @overload
#     def SetCategoryList(self, clist: list[str], ctype: type) -> None: ...
#     @overload
#     def SetCategoryList(self, arg0: list[str]) -> None: ...
#     @overload
#     def SetCategoryListType(self, ctype: type) -> None: ...
#     @overload
#     def SetCategoryListType(self) -> None: ...
#     @overload
#     def SetDataBlockList(self, dblist: list[str], dbtype: type) -> None: ...
#     @overload
#     def SetDataBlockList(self, arg0: list[str]) -> None: ...
#     @overload
#     def SetDataBlockListType(self, dbtype: type) -> None: ...
#     @overload
#     def SetDataBlockListType(self) -> None: ...

# class DicFile(CifFile):
#     @overload
#     def __init__(self, fileMode: eFileMode, objFileName: str, verbose: bool, caseSense, maxLineLength: int, nullValue: str) -> None: ...
#     @overload
#     def __init__(self, arg0: eFileMode, arg1: str) -> None: ...
#     @overload
#     def __init__(self, arg0: eFileMode, arg1: str, arg2: bool) -> None: ...
#     @overload
#     def __init__(self, arg0: eFileMode, arg1: str, arg2: bool, arg3) -> None: ...
#     @overload
#     def __init__(self, arg0: eFileMode, arg1: str, arg2: bool, arg3, arg4: int) -> None: ...
#     @overload
#     def __init__(self, verbose: bool, caseSense, maxLineLength: int, nullValue: str) -> None: ...
#     @overload
#     def __init__(self) -> None: ...
#     @overload
#     def __init__(self, arg0: bool) -> None: ...
#     @overload
#     def __init__(self, arg0: bool, arg1) -> None: ...
#     @overload
#     def __init__(self, arg0: bool, arg1, arg2: int) -> None: ...
#     def Compress(self, ddl: CifFile) -> None: ...
#     def GetFormatTable(self) -> ISTable: ...
#     def GetRefFile(self) -> CifFile: ...
#     @overload
#     def WriteFormatted(self, cifFileName: str, formatP: ISTable) -> int: ...
#     @overload
#     def WriteFormatted(self, arg0: str) -> int: ...
#     @overload
#     def WriteFormatted(self, cifFileName: str, ddl: TableFile, formatP: ISTable) -> int: ...
#     @overload
#     def WriteFormatted(self, arg0: str, arg1: TableFile) -> int: ...
#     def WriteItemAliases(self, fileName: str) -> None: ...

# class DictDataInfo:
#     def __init__(self, dictObjCont: DictObjCont) -> None: ...
#     def GetCatAttribute(self, catName: str, refCatName: str, refAttrName: str) -> list[str]: ...
#     def GetCatKeys(self, catName: str) -> list[str]: ...
#     def GetItemAttribute(self, itemName: str, refCatName: str, refAttrName: str) -> list[str]: ...
#     def GetItemsNames(self) -> list[str]: ...
#     def GetVersion(self, version: str) -> str: ...
#     def IsCatDefined(self, catName: str) -> bool: ...
#     def IsItemDefined(self, itemName: str) -> bool: ...

class ISTable:
    class eSearchDir:
        # __members__: ClassVar[dict] = ...  # read-only
        # __entries: ClassVar[dict] = ...
        eBACKWARD: ClassVar[ISTable.eSearchDir] = ...
        eFORWARD: ClassVar[ISTable.eSearchDir] = ...
        def __init__(self, value: int) -> None: ...
        # def __eq__(self, other: object) -> bool: ...
        # def __hash__(self) -> int: ...
        # def __index__(self) -> int: ...
        # def __int__(self) -> int: ...
        # def __ne__(self, other: object) -> bool: ...
        @property
        def name(self) -> str: ...
        @property
        def value(self) -> int: ...

#     class eSearchType:
#         __members__: ClassVar[dict] = ...  # read-only
#         __entries: ClassVar[dict] = ...
#         eEQUAL: ClassVar[ISTable.eSearchType] = ...
#         eGREATER_THAN: ClassVar[ISTable.eSearchType] = ...
#         eGREATER_THAN_OR_EQUAL: ClassVar[ISTable.eSearchType] = ...
#         eLESS_THAN: ClassVar[ISTable.eSearchType] = ...
#         eLESS_THAN_OR_EQUAL: ClassVar[ISTable.eSearchType] = ...
#         def __init__(self, value: int) -> None: ...
#         def __eq__(self, other: object) -> bool: ...
#         def __hash__(self) -> int: ...
#         def __index__(self) -> int: ...
#         def __int__(self) -> int: ...
#         def __ne__(self, other: object) -> bool: ...
#         @property
#         def name(self) -> str: ...
#         @property
#         def value(self) -> int: ...

#     class eTableDiff:
#         __members__: ClassVar[dict] = ...  # read-only
#         __entries: ClassVar[dict] = ...
#         eCASE_SENSE: ClassVar[ISTable.eTableDiff] = ...
#         eCELLS: ClassVar[ISTable.eTableDiff] = ...
#         eCOL_NAMES: ClassVar[ISTable.eTableDiff] = ...
#         eEXTRA: ClassVar[ISTable.eTableDiff] = ...
#         eLESS_COLS: ClassVar[ISTable.eTableDiff] = ...
#         eLESS_ROWS: ClassVar[ISTable.eTableDiff] = ...
#         eMISSING: ClassVar[ISTable.eTableDiff] = ...
#         eMORE_COLS: ClassVar[ISTable.eTableDiff] = ...
#         eMORE_ROWS: ClassVar[ISTable.eTableDiff] = ...
#         eNONE: ClassVar[ISTable.eTableDiff] = ...
#         def __init__(self, value: int) -> None: ...
#         def __eq__(self, other: object) -> bool: ...
#         def __hash__(self) -> int: ...
#         def __index__(self) -> int: ...
#         def __int__(self) -> int: ...
#         def __ne__(self, other: object) -> bool: ...
#         @property
#         def name(self) -> str: ...
#         @property
#         def value(self) -> int: ...
#     eBACKWARD: ClassVar[ISTable.eSearchDir] = ...
#     eCASE_SENSE: ClassVar[ISTable.eTableDiff] = ...
#     eCELLS: ClassVar[ISTable.eTableDiff] = ...
#     eCOL_NAMES: ClassVar[ISTable.eTableDiff] = ...
#     eEQUAL: ClassVar[ISTable.eSearchType] = ...
#     eEXTRA: ClassVar[ISTable.eTableDiff] = ...
#     eFORWARD: ClassVar[ISTable.eSearchDir] = ...
#     eGREATER_THAN: ClassVar[ISTable.eSearchType] = ...
#     eGREATER_THAN_OR_EQUAL: ClassVar[ISTable.eSearchType] = ...
#     eLESS_COLS: ClassVar[ISTable.eTableDiff] = ...
#     eLESS_ROWS: ClassVar[ISTable.eTableDiff] = ...
#     eLESS_THAN: ClassVar[ISTable.eSearchType] = ...
#     eLESS_THAN_OR_EQUAL: ClassVar[ISTable.eSearchType] = ...
#     eMISSING: ClassVar[ISTable.eTableDiff] = ...
#     eMORE_COLS: ClassVar[ISTable.eTableDiff] = ...
#     eMORE_ROWS: ClassVar[ISTable.eTableDiff] = ...
#     eNONE: ClassVar[ISTable.eTableDiff] = ...
    @overload
    def __init__(self, colCaseSense: bool) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, orient: str, colCaseSense: bool) -> None: ...
    @overload
    def __init__(self, arg0: str) -> None: ...
    @overload
    def __init__(self, name: str, colCaseSense: bool) -> None: ...
    #@overload
    # def __init__(self, arg0: str) -> None: ...
    @overload
    def __init__(self, name: str, orient: str, colCaseSense: bool) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: str) -> None: ...
    @overload
    def __init__(self, inTable: ISTable) -> None: ...
    @overload
    def AddColumn(self, colName: str, col: list[str]) -> None: ...
    @overload
    def AddColumn(self, arg0: str) -> None: ...
    @overload
    def AddRow(self, row: list[str]) -> int: ...
    @overload
    def AddRow(self) -> int: ...
#     def ClearColumn(self, colName: str) -> None: ...
#     def ClearRow(self, rowIndex: int) -> None: ...
#     @overload
#     def CreateIndex(self, indexName: str, colNames: list[str], unique: int) -> None: ...
#     @overload
#     def CreateIndex(self, arg0: str, arg1: list[str]) -> None: ...
#     def CreateKey(self, colNames: list[str]) -> None: ...
#     def DeleteColumn(self, colName: str) -> None: ...
#     def DeleteIndex(self, indexName: str) -> None: ...
#     def DeleteKey(self) -> None: ...
#     def DeleteRow(self, rowIndex: int) -> None: ...
#     def DeleteRows(self, rows: list[int]) -> None: ...
#     def FillColumn(self, colName: str, col: list[str]) -> None: ...
    def FillRow(self, rowIndex: int, row: list[str]) -> None: ...
#     def FindDuplicateRows(self, duplRows: list[tuple[int, int]], colNames: list[str], keepDuplRows: bool, searchDir: ISTable.eSearchDir) -> list[tuple[int, int]]: ...
#     @overload
#     def FindFirst(self, targets: list[str], colNames: list[str], indexName: str) -> int: ...
#     @overload
#     def FindFirst(self, arg0: list[str], arg1: list[str]) -> int: ...
#     def GetColCaseSense(self, *args, **kwargs): ...
#     @overload
#     def GetColumn(self, col: list[str], colName: str) -> list[str]: ...
#     @overload
#     def GetColumn(self, col: list[str], colName: str, fromRowIndex: int, toRowIndex: int) -> list[str]: ...
#     @overload
#     def GetColumn(self, col: list[str], colName: str, rowIndex: list[int]) -> list[str]: ...
#     @overload
#     def GetColumn(self, col: list[str], colName: str, indexName: str) -> list[str]: ...
    def GetColumnNames(self) -> List[str]: ...
#     def GetColumnsIndices(self, colIndices: list[int], colNames: list[str]) -> list[int]: ...
#     def GetDataType(self, colName: str) -> int: ...
#     def GetLastRowIndex(self) -> int: ...
#     def GetModified(self) -> bool: ...
#     def GetName(self) -> str: ...
#     def GetNumColumns(self) -> int: ...
#     def GetNumIndices(self) -> int: ...
    def GetNumRows(self) -> int: ...
#     def GetObject(self, index: int, ser: Serializer) -> int: ...
    @overload
    def GetRow(self, row: List[str], rowIndex: int, fromColName: str, toColName: str) -> List[str]: ...
    @overload
    def GetRow(self, rowIndex: int) ->List[str]: ...
#     def IndexExists(self, indexName: str) -> bool: ...
#     @overload
#     def InsertColumn(self, colName: str, afColName: str, col: list[str]) -> None: ...
#     @overload
#     def InsertColumn(self, arg0: str, arg1: str) -> None: ...
#     @overload
#     def InsertRow(self, atRowIndex: int, row: list[str]) -> int: ...
#     @overload
#     def InsertRow(self, arg0: int) -> int: ...
#     def IsColumnPresent(self, colName: str) -> bool: ...
#     def PrintDiff(self, inTable: ISTable) -> tuple[bool, ISTable]: ...
#     def Read(self, indexInFile: int) -> None: ...
#     def RenameColumn(self, oldColName: str, newColName: str) -> None: ...
#     @overload
#     def Search(self, res: list[int], target: str, colName: str, fromRowIndex: int, searchDir: ISTable.eSearchDir, searchType: ISTable.eSearchType) -> list[int]: ...
#     @overload
#     def Search(self, res: list[int], targets: list[str], colNames: list[str], fromRowIndex: int, searchDir: ISTable.eSearchDir, searchType: ISTable.eSearchType, indexName: str) -> list[int]: ...
#     def SetFlags(self, colName: str, flags: int) -> None: ...
#     def SetModified(self, modified: bool) -> None: ...
#     def SetName(self, name: str) -> None: ...
#     def SetSerializer(self, ser: Serializer) -> None: ...
#     def UpdateCell(self, rowIndex: int, colName: str, value: str) -> None: ...
#     def Write(self) -> int: ...
#     def WriteObject(self, ser: Serializer, size: int) -> tuple[int, Serializer, int]: ...
#     def assign(self, inTable: ISTable) -> ISTable: ...
#     def __call__(self, rowIndex: int, colName: str) -> str: ...
#     def __eq__(self, inTable: ISTable) -> ISTable.eTableDiff: ...

class TableFile:
    class eStatusInd:
#        __members__: ClassVar[dict] = ...  # read-only
#        __entries: ClassVar[dict] = ...
        eCLEAR_STATUS: ClassVar[TableFile.eStatusInd] = ...
        eDUPLICATE_BLOCKS: ClassVar[TableFile.eStatusInd] = ...
        eUNNAMED_BLOCKS: ClassVar[TableFile.eStatusInd] = ...
        def __init__(self, value: int) -> None: ...
#        def __eq__(self, other: object) -> bool: ...
#        def __hash__(self) -> int: ...
#        def __index__(self) -> int: ...
#        def __int__(self) -> int: ...
#        def __ne__(self, other: object) -> bool: ...
        @property
        def name(self) -> str: ...
        @property
        def value(self) -> int: ...
    eCLEAR_STATUS: ClassVar[TableFile.eStatusInd] = ...
    eDUPLICATE_BLOCKS: ClassVar[TableFile.eStatusInd] = ...
    eUNNAMED_BLOCKS: ClassVar[TableFile.eStatusInd] = ...
    @overload
    def __init__(self, caseSense: bool) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, fileMode: eFileMode, fileName: str, caseSense: bool) -> None: ...
    @overload
    def __init__(self, arg0: eFileMode, arg1: str) -> None: ...
    def AddBlock(self, blockName: str) -> str: ...
    def Close(self) -> None: ...
    def Flush(self) -> None: ...
    def GetBlock(self, blockName: str) -> Block: ...
    def GetBlockNames(self, blockNames: list[str]) -> list[str]: ...
    # def GetCaseSensitivity(self, *args, **kwargs): ...
    def GetFileMode(self) -> eFileMode: ...
    def GetFileName(self) -> str: ...
    def GetFirstBlockName(self) -> str: ...
    def GetNumBlocks(self) -> int: ...
    def GetStatusInd(self) -> int: ...
    def IsBlockPresent(self, blockName: str) -> bool: ...
    def RenameBlock(self, oldBlockName: str, newBlockName: str) -> str: ...
    def RenameFirstBlock(self, newBlockName: str) -> str: ...
    def Serialize(self, fileName: str) -> None: ...

class eTypeCode:
 #   __members__: ClassVar[dict] = ...  # read-only
 #   __entries: ClassVar[dict] = ...
    eTYPE_CODE_BIGINT: ClassVar[eTypeCode] = ...
    eTYPE_CODE_DATETIME: ClassVar[eTypeCode] = ...
    eTYPE_CODE_FLOAT: ClassVar[eTypeCode] = ...
    eTYPE_CODE_INT: ClassVar[eTypeCode] = ...
    eTYPE_CODE_NONE: ClassVar[eTypeCode] = ...
    eTYPE_CODE_STRING: ClassVar[eTypeCode] = ...
    eTYPE_CODE_TEXT: ClassVar[eTypeCode] = ...
    def __init__(self, value: int) -> None: ...
 #   def __eq__(self, other: object) -> bool: ...
 #   def __hash__(self) -> int: ...
 #   def __index__(self) -> int: ...
 #   def __int__(self) -> int: ...
 #   def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

# class type:
#     __members__: ClassVar[dict] = ...  # read-only
#     A: ClassVar[type] = ...
#     D: ClassVar[type] = ...
#     __entries: ClassVar[Dict] = ...
#     def __init__(self, value: int) -> None: ...
#     def __eq__(self, other: object) -> bool: ...
#     def __hash__(self) -> int: ...
#     def __index__(self) -> int: ...
#     def __int__(self) -> int: ...
#     def __ne__(self, other: object) -> bool: ...
#     @property
#     def name(self) -> str: ...
#     @property
#     def value(self) -> int: ...

#def CheckCif(cifFileP: CifFile, dictFileP: DicFile, cifFileName: str, extraCifChecks: bool) -> tuple[CifFile, DicFile]: ...
#def CheckDict(dictFileP: DicFile, ddlFileP: DicFile, dictFileName: str, extraDictChecks: bool) -> tuple[DicFile, DicFile]: ...
#def DataCorrection(cifFile: CifFile, dicRef: DicFile) -> tuple[CifFile, DicFile]: ...
#def GetDictFile(ddlFileP: DicFile, dictFileName: str, dictSdbFileName: str, verbose: bool, fileMode: eFileMode) -> tuple[DicFile, DicFile]: ...
#def ParseCif(fileName: str, verbose: bool, caseSense, maxLineLength: int, nullValue: str, parseLogFileName: str) -> CifFile: ...
#def ParseCifSelective(fileName: str, readDef: CifFileReadDef, verbose: bool, intCaseSense: int, maxLineLength: int, nullValue: str, parseLogFileName: str) -> CifFile: ...
def ParseCifSimple(fileName: str, verbose: bool, intCaseSense: int, maxLineLength: int, nullValue: str, parseLogFileName: str) -> CifFile: ...
#def ParseCifString(cifString: str, verbose: bool, caseSense, maxLineLength: int, nullValue: str) -> CifFile: ...
#def ParseDict(dictFileName: str, ddlFileP: DicFile, verbose: bool) -> tuple[DicFile, DicFile]: ...
