from _typeshed import Incomplete
from typing import Any, Dict, List, Optional, TextIO, Tuple, Union
from mmcif.api.DataCategoryBase import DataCategoryBase as DataCategoryBase

__docformat__: str
logger: Incomplete

class DataCategory(DataCategoryBase):
    def __init__(self, name: str, attributeNameList: Optional[List[str]] = None, rowList: Optional[List[Any]] = None, raiseExceptions: bool = True, copyInputData: bool = True) -> None: ...
    def setVerboseMode(self, boolVal: bool) -> None: ...
    def getCurrentAttribute(self) -> Optional[str]: ...
    def getRowIndex(self) -> int: ...
    def getFullRow(self, index: int) -> List[str]: ...
    def getAttributeListWithOrder(self) -> List[str]: ...
    def appendAttributeExtendRows(self, attributeName: str, defaultValue: str = '?') -> int: ...
    def getValue(self, attributeName: Optional[str] = None, rowIndex: Optional[int] = None) -> str: ...
    def getValueOrDefault(self, attributeName: Optional[str] = None, rowIndex: Optional[int] = None, defaultValue: Optional[str] = '') -> str: ...
    def getFirstValueOrDefault(self, attributeNameList: List[str], rowIndex: int = 0, defaultValue: str = '') -> str: ...
    def setValue(self, value: Optional[Union[str, int, float]], attributeName: Optional[str] = None, rowIndex: Optional[int] = None) -> bool: ...
    def replaceValue(self, oldValue: str, newValue: str, attributeName: str) -> int: ...
    def replaceSubstring(self, oldValue: str, newValue: str, attributeName: str) -> int: ...
    def selectIndices(self, attributeValue: str, attributeName: str) -> List[int]: ...
    def selectIndicesFromList(self, attributeValueList: List[str], attributeNameList: List[str]) -> List[int]: ...
    def selectValuesWhere(self, attributeName: str, attributeValueWhere: str, attributeNameWhere: str, returnCount: int = 0) -> List[str]: ...
    def selectValueListWhere(self, attributeNameList: List[str], attributeValueWhere: str, attributeNameWhere: str, returnCount: int = 0) -> List[str]: ...
    def selectValuesWhereConditions(self, attributeName: str, conditionsD: Dict[str, str], returnCount: int = 0) -> List[str]: ...
    def countValuesWhereConditions(self, conditionsD: Dict[str, str]) -> int: ...
    def countValuesWhereOpConditions(self, conditionTupleListL: Tuple[str, str, str]) -> int: ...
    def selectIndicesWhereOpConditions(self, conditionTupleList: Tuple[str, str, str]) -> List[int]: ...
    def selectValuesWhereOpConditions(self, attributeName: str, conditionTupleList: Tuple[str, str, str]) -> List[str]: ...
    def getCombinationCounts(self, attributeList: List[str]) -> Dict[str, int]: ...
    def getCombinationCountsWithConditions(self, attributeList: List[str], conditionTupleList: List[Tuple[str, str, str]]) -> Dict[str, int]: ...
    # def invokeAttributeMethod(self, attributeName, mType, method, db) -> None: ...
    # def invokeCategoryMethod(self, mType: str, method: Any, db) -> None: ...
    def printIt(self, fh: TextIO = ...) -> None: ...
    def dumpIt(self, fh: TextIO =...) -> None: ...
