from _typeshed import Incomplete
from collections import UserList
from typing import Dict, List, Tuple, Any, Optional

__docformat__: str
logger: Incomplete

class DataCategoryBase(UserList[DataCategoryBase]):
    data: Incomplete
    def __init__(self, name: str, attributeNameList: Optional[List[str]] = None, rowList: Optional[List[Any]]=None, raiseExceptions: bool = True, copyInputData: bool = True) -> None: ...
    def append(self, row: List[str]) -> bool: ...  # type: ignore[override]
    def extend(self, rowList: List[List[str]]) -> bool: ...  # type: ignore[override]
    def setName(self, name: str) -> None: ...
    def setRowList(self, rowList: List[List[str]]) -> None: ...
    def setAttributeNameList(self, attributeNameList: List[str]) -> None: ...
    def appendAttribute(self, attributeName: str) -> int: ...
    def renameAttributes(self, mapDict: Dict[str, str]) -> bool: ...
    def get(self) -> Tuple[str, List[str], List[List[Any]]]: ...
    def getName(self) -> str: ...
    def getAttributeList(self) -> List[str]: ...
    def getAttributeCount(self) -> int: ...
    def getAttributeIndex(self, attributeName: str) -> int: ...
    def getAttributeIndexDict(self) -> Dict[str, int]: ...
    def getIndex(self, attributeName: str) -> int: ...
    def hasAttribute(self, attributeName: str) -> bool: ...
    def getItemNameList(self) -> List[str]: ...
    def getRowList(self) -> List[List[str]]: ...
    def getRowCount(self) -> int: ...
    def getRow(self, index: int) -> List[str]: ...
    def getColumn(self, index: int) -> List[str]: ...
    def getRowAttributeDict(self, index: int) -> Dict[str, str]: ...
    def getRowItemDict(self, index: int) -> Dict[str, str]: ...
    def getAttributeValueList(self, attributeName: str) -> List[str]: ...
    def getAttributeUniqueValueList(self, attributeName: str) -> List[str]: ...
    def removeRow(self, index: int) -> bool: ...
    def removeRows(self, indexList: List[int]) -> bool: ...
    def removeDuplicateRows(self) -> bool: ...
    def removeAttribute(self, attributeName: str) -> bool: ...
    def setMapping(self, mType: str) -> bool: ...
    # def __iter__(self): ...
    # def __getitem__(self, idx): ...
    # def __setitem__(self, idx, value) -> None: ...
    def cmpAttributeNames(self, dcObj: DataCategoryBase) -> Tuple[List[str], List[str], List[str]]: ...
    def cmpAttributeValues(self, dcObj: DataCategoryBase, ignoreOrder: bool = True, **kwargs: Any) -> List[Tuple[str, bool]]: ...
    # def __eq__(self, other): ...
    # def __ne__(self, other): ...
    # def __hash__(self): ...
