from _typeshed import Incomplete
from typing import Any, List, Optional, Tuple

from mmcif.api.DataCategory import DataCategory as DataCategory
from mmcif.api.DataCategoryBase import DataCategoryBase as DataCategoryBase
from mmcif.api.PdbxContainers import CifName as CifName
from mmcif.api.DictionaryApi import DictionaryApi

__docformat__: str
logger: Incomplete

class DataCategoryHints:
    def __init__(self, **kwargs: str) -> None: ...
    def inMolStarIntHints(self, name: str) -> bool: ...
    def getPdbxItemType(self, typeCode: str) -> str: ...

class DataCategoryTyped(DataCategory):
    def __init__(self, dataCategoryObj: DataCategory, dictionaryApi: Optional[DictionaryApi]=None, raiseExceptions: bool = True, copyInputData: bool = True, ignoreCastErrors: bool = False, useCifUnknowns: bool = True, missingValueString: Optional[str]=None, missingValueInteger: Optional[int]=None, missingValueFloat: Optional[float]=None, **kwargs: Any) -> None: ...
    def applyTypes(self, ignoreCastErrors: bool = False, useCifUnknowns: bool = True, missingValueString: Optional[str] = None, missingValueInteger: Optional[int]  =None, missingValueFloat: Optional[float] = None) -> bool: ...
    def getAttributeInfo(self, atName: str) -> Tuple[str, bool]: ...
    def applyStringTypes(self) -> bool: ...
    def cmpAttributeValues(self, dcObj: DataCategoryBase, ignoreOrder: bool = True, **kwargs: Any) -> List[Any]: ...
