from _typeshed import Incomplete
from typing import List, Optional, Tuple
from mmcif.api.DataCategory import DataCategory as DataCategory

__docformat__: str
logger: Incomplete

class DataCategoryFormatted(DataCategory):
    def __init__(self, dataCategoryObj: DataCategory, preferDoubleQuotes: bool = True) -> None: ...
    def getValueFormatted(self, attributeName: Optional[str] = None, rowIndex: Optional[int] = None) -> str: ...
    def getValueFormattedByIndex(self, attributeIndex: int, rowIndex: int) -> str: ...
    def getAttributeValueMaxLengthList(self, steps: int = 1) -> List[int]: ...
    def getFormatTypeList(self, steps: int = 1) -> Tuple[List[str], List[str]]: ...
