from _typeshed import Incomplete
from mmcif.api.DataCategory import DataCategory as DataCategory
from mmcif.api.DictionaryApi import DictionaryApi as DictionaryApi

__docformat__: str
logger: Incomplete

class MethodUtils:
    def __init__(self, dictContainerList, verbose: bool = False) -> None: ...
    def setDataContainerList(self, dataContainerList) -> None: ...
    def getDataContainerList(self): ...
    def getDictionary(self): ...
    def getMethods(self): ...
    def getMethod(self, mId): ...
    def invokeMethods(self, fh=...) -> None: ...
    def dumpMethods(self, fh=...) -> None: ...
    def dumpDictionary(self, fh=...) -> None: ...
    def dumpDataFile(self, fh=...) -> None: ...
