from _typeshed import Incomplete
from typing import Optional, TextIO

__docformat__: str

# class MethodDefinition:
#     methodId: Incomplete
#     language: Incomplete
#     code: Incomplete
#     inline: Incomplete
#     priority: Incomplete
#     implementationSource: Incomplete
#     implementation: Incomplete
#     def __init__(self, methodId: str, code: str = 'calculate', language: str = 'Python', inline: Optional[str] = None, priority: str = None, implementation: str = None, implementationSource: str = 'inline') -> None: ...
#     def getId(self): ...
#     def getLanguage(self): ...
#     def getCode(self): ...
#     def getInline(self): ...
#     def getImplementation(self): ...
#     def getImplementationSource(self): ...
#     def getPriority(self): ...
#     def printIt(self, fh=...) -> None: ...

class MethodReference:
    methodId: Incomplete
    type: Incomplete
    categoryName: Incomplete
    attributeName: Incomplete
    def __init__(self, methodId: str, mType: str = 'attribute', category: Optional[str] = None, attribute: Optional[str] = None) -> None: ...
    def getId(self) -> str: ...
    def getType(self) -> str: ...
    def getCategoryName(self) -> Optional[str]: ...
    def getAttributeName(self) -> Optional[str]: ...
    def printIt(self, fh: TextIO =...) -> None: ...
