from _typeshed import Incomplete

from typing import Any, Dict, List, Optional, TextIO

from mmcif.api.DataCategoryBase import DataCategoryBase
from mmcif.api.DataCategory import DataCategory

__docformat__: str
logger: Incomplete

class CifName:
    def __init__(self) -> None: ...
    @staticmethod
    def categoryPart(name: str) -> str: ...
    @staticmethod
    def attributePart(name: str) -> Optional[str]: ...
    @staticmethod
    def itemName(categoryName: str, attributeName: str) -> Optional[str]: ...  # Overload possible

class ContainerBase:
    def __init__(self, name: str) -> None: ...
    # def __eq__(self, other): ...
    # def __hash__(self): ...
    def getObjCatalog(self) -> Dict[str, DataCategoryBase]: ...
    def getPropCatalog(self) -> Dict[str, Any]: ...
    def setProp(self, propName: str, value: Any) -> bool: ...
    def getProp(self, propName: str) -> Optional[Any]: ...
    def getType(self) -> Optional[str]: ...
    def setType(self, cType: str) -> None: ...
    def getName(self) -> str: ...
    def setName(self, name: str) -> None: ...
    def exists(self, name: str) -> bool: ...
    def getObj(self, name: str) -> Optional[DataCategory]: ...
    def getObjNameList(self) -> List[str]: ...
    def append(self, obj: DataCategoryBase) -> None: ...
    def replace(self, obj: DataCategoryBase) -> None: ...
    def printIt(self, fh: TextIO=..., pType: str = 'brief') -> None: ...
    def rename(self, curName: str, newName: str) -> bool: ...
    def copy(self, curName: str, newName: str) -> bool: ...
    def remove(self, curName: str) -> bool: ...
    def merge(self, container: ContainerBase) -> bool: ...
    def filterObjectNameList(self, lastInOrder: Optional[List[str]]=None, selectOrder: Optional[List[str]]=None) -> List[str]: ...
    def toJSON(self) -> Dict[str, DataCategoryBase]: ...

class DefinitionContainer(ContainerBase):
    def __init__(self, name: str) -> None: ...
    def isCategory(self) -> bool: ...
    def isAttribute(self) -> bool: ...
    def getGlobal(self) -> bool: ...
    def printIt(self, fh: TextIO =..., pType: str = 'brief') -> None: ...

class DataContainer(ContainerBase):
    def __init__(self, name: str) -> None: ...
    def invokeDataBlockMethod(self, mType: str, method: str, db: str) -> None: ...
    def setGlobal(self) -> None: ...
    def getGlobal(self) -> bool: ...

class SaveFrameContainer(ContainerBase):
    def __init__(self, name: str) -> None: ...
